package com.example.palabras

import com.example.palabras.data.Country


// Constants with max number of words per game and
// the score increase  on correct guesses
const val MAX_NO_OF_WORDS = 10
const val SCORE_INCREASE = 20

// Lists with groups of words
val countriesList: List<Country> = listOf(
    Country("afghanistan", R.drawable.afghanistan),
    Country("albania", R.drawable.albania),
    Country("algeria", R.drawable.algeria),
            Country("andorra", R.drawable.andorra),
            Country("angola", R.drawable.angola),
            Country("antigua", R.drawable.antigua_and_barbuda),
            Country("argentina", R.drawable.argentina),
            Country("armenia", R.drawable.armenia),
            Country("australia", R.drawable.australia),
            Country("austria", R.drawable.austria),
            Country("azerbaijan", R.drawable.azerbaijan),
            Country("bahamas", R.drawable.bahamas),
            Country("bahrain", R.drawable.bahrain),
            Country("bangladesh", R.drawable.bangladesh),
            Country("barbados", R.drawable.barbados),
            Country("belarus", R.drawable.belarus),
            Country("belgium", R.drawable.belgium),
            Country("belize", R.drawable.belize),
            Country("benin", R.drawable.benin),
            Country("bhutan", R.drawable.bhutan),
            Country("bolivia", R.drawable.bolivia),
            Country("bosnia herzegovina", R.drawable.bosnia),
            Country("botswana", R.drawable.botswana),
            Country("brazil", R.drawable.brazil),
            Country("brunei", R.drawable.brunei),
            Country("bulgaria", R.drawable.bulgaria),
            Country("burkina", R.drawable.burkina_faso),
            Country("burundi", R.drawable.burundi),
            Country("cambodia", R.drawable.cambodia),
            Country("cameroon", R.drawable.cameroon),
            Country("canada", R.drawable.canada),
            Country("cape verde", R.drawable.cape_verde),
            Country("chad", R.drawable.chad),
            Country("chile", R.drawable.chile),
            Country("china", R.drawable.china),
            Country("colombia", R.drawable.colombia),
            Country("comoros", R.drawable.comoros),
            Country("congo", R.drawable.democratic_republic_of_the_congo),
            Country("costa rica", R.drawable.costa_rica),
            Country("croatia", R.drawable.croatia),
            Country("cuba", R.drawable.cuba),
            Country("cyprus", R.drawable.cyprus),
            Country("czech republic", R.drawable.czech_republic),
            Country("denmark", R.drawable.denmark),
            Country("djibouti", R.drawable.djibouti),
            Country("dominica", R.drawable.dominica),
            Country("dominican republic", R.drawable.dominican_republic),
            Country("ecuador", R.drawable.ecuador),
            Country("egypt", R.drawable.egypt),
            Country("el salvador", R.drawable.el_salvador),
            Country("equatorial guinea", R.drawable.equatorial_guinea),
            Country("eritrea", R.drawable.eritrea),
            Country("estonia", R.drawable.estonia),
            Country("ethiopia", R.drawable.ethiopia),
            Country("fiji", R.drawable.fiji),
            Country("finland", R.drawable.finland),
            Country("france", R.drawable.france),
            Country("gabon", R.drawable.gabon),
            Country("gambia", R.drawable.gambia),
            Country("georgia", R.drawable.georgia),
            Country("germany", R.drawable.germany),
            Country("ghana", R.drawable.ghana),
                Country("greece", R.drawable.greece),
            Country("grenada", R.drawable.grenada),
            Country("guatemala", R.drawable.guatemala),
            Country("guinea", R.drawable.guinea),
            Country("guinea-Bissau", R.drawable.guinea_bissau),
            Country("guyana", R.drawable.guyana),
            Country("haiti", R.drawable.haiti),
            Country("honduras", R.drawable.honduras),
            Country("hungary", R.drawable.hungary),
            Country("iceland", R.drawable.iceland),
            Country("india", R.drawable.india),
            Country("indonesia", R.drawable.indonesia),
            Country("iran", R.drawable.iran),
            Country("iraq", R.drawable.iraq),
            Country("ireland", R.drawable.ireland),
            Country("italy", R.drawable.italy),
    //"ivory coast", R.drawable.
            Country("jamaica", R.drawable.jamaica),
            Country("japan", R.drawable.japan),
            Country("jordan", R.drawable.jordan),
            Country("kazakhstan", R.drawable.kazakhstan),
            Country("kenya", R.drawable.kenya),
            Country("kiribati", R.drawable.kiribati),
            Country("korea north", R.drawable.north_korea),
            Country("korea south", R.drawable.south_korea),
            Country("kuwait", R.drawable.kuwait),
            Country("kyrgyzstan", R.drawable.kyrgyzstan),
            Country("laos", R.drawable.laos),
            Country("latvia", R.drawable.latvia),
            Country("lebanon", R.drawable.lebanon),
            Country("lesotho", R.drawable.lesotho),
            Country("liberia", R.drawable.liberia),
                Country("libya", R.drawable.libya),
            Country("liechtenstein", R.drawable.liechtenstein),
            Country("lithuania", R.drawable.lithuania),
            Country("luxembourg", R.drawable.luxembourg),
            Country("macedonia", R.drawable.macedonia),
            Country("madagascar", R.drawable.madagascar),
            Country("malawi", R.drawable.malawi),
            Country("malaysia", R.drawable.malaysia),
            Country("maldives", R.drawable.maldives),
            Country("mali", R.drawable.mali),
            Country("malta", R.drawable.malta),
            Country("marshall islands", R.drawable.marshall_islands),
            Country("mauritania", R.drawable.mauritania),
            Country("mauritius", R.drawable.mauritius),
            Country("mexico", R.drawable.mexico),
            Country("micronesia", R.drawable.micronesia),
            Country("moldova", R.drawable.moldova),
            Country("monaco", R.drawable.monaco),
            Country("mongolia", R.drawable.mongolia),
    //"montenegro", R.drawable.
            Country("morocco", R.drawable.morocco),
            Country("mozambique", R.drawable.mozambique),
            Country("myanmar", R.drawable.myanmar),
            Country("namibia", R.drawable.namibia),
            Country("nauru", R.drawable.nauru),
            Country("nepal", R.drawable.nepal),
            Country("netherlands", R.drawable.netherlands),
            Country("new zealand", R.drawable.new_zealand),
            Country("nicaragua", R.drawable.nicaragua),
            Country("niger", R.drawable.niger),
            Country("nigeria", R.drawable.nigeria),
            Country("norway", R.drawable.norway),
            Country("oman", R.drawable.oman),
            Country("pakistan", R.drawable.pakistan),
            Country("palau", R.drawable.palau),
                Country("panama", R.drawable.panama),
            Country("papua new guinea", R.drawable.papua_new_guinea),
            Country("paraguay", R.drawable.paraguay),
            Country("peru", R.drawable.peru),
            Country("philippines", R.drawable.philippines),
            Country("poland", R.drawable.poland),
            Country("portugal", R.drawable.portugal),
            Country("qatar", R.drawable.qatar),
            Country("romania", R.drawable.romania),
            Country("russia", R.drawable.russian_federation),
            Country("rwanda", R.drawable.rwanda),
            Country("st lucia", R.drawable.saint_lucia),
            Country("samoa", R.drawable.samoa),
            Country("san marino", R.drawable.san_marino),
            Country("saudi arabia", R.drawable.saudi_arabia),
            Country("senegal", R.drawable.senegal),
            Country("serbia", R.drawable.serbia_and_montenegro),
            Country("seychelles", R.drawable.seychelles),
            Country("sierra leone", R.drawable.sierra_leone),
            Country("singapore", R.drawable.singapore),
            Country("slovakia", R.drawable.slovakia),
            Country("slovenia", R.drawable.slovenia),
            Country("solomon islands", R.drawable.soloman_islands),
            Country("somalia", R.drawable.somalia),
            Country("south africa", R.drawable.south_africa),
    //"south sudan", R.drawable.
            Country("spain", R.drawable.spain),
            Country("sri lanka", R.drawable.sri_lanka),
            Country("sudan", R.drawable.sudan),
            Country("suriname", R.drawable.suriname),
            Country("swaziland", R.drawable.swaziland),
            Country("sweden", R.drawable.sweden),
            Country("switzerland", R.drawable.switzerland),
            Country("syria", R.drawable.syria),
            Country("taiwan", R.drawable.taiwan),
            Country("tajikistan", R.drawable.tajikistan),
            Country("tanzania", R.drawable.tanzania),
            Country("thailand", R.drawable.thailand),
            Country("togo", R.drawable.togo),
            Country("tonga", R.drawable.tonga),
            Country("trinidad & tobago", R.drawable.trinidad_and_tobago),
            Country("tunisia", R.drawable.tunisia),
            Country("turkey", R.drawable.turkey),
            Country("turkmenistan", R.drawable.turkmenistan),
            Country("tuvalu", R.drawable.tuvalu),
            Country("uganda", R.drawable.uganda),
            Country("ukraine", R.drawable.ukraine),
            Country("united arab emirates", R.drawable.saudi_arabia),
            Country("united kingdom", R.drawable.united_kingdom),
            Country("united states", R.drawable.united_states_of_america),
            Country("uruguay", R.drawable.uruguay),
            Country("uzbekistan", R.drawable.uzbekistan),
            Country("vanuatu", R.drawable.vanuatu),
            Country("vatican city", R.drawable.vatican_city),
            Country("venezuela", R.drawable.venezuela),
            Country("vietnam", R.drawable.vietnam),
            Country("yemen", R.drawable.yemen),
            Country("zambia", R.drawable.zambia),
            Country("zimbawe", R.drawable.zimbabwe)
)



