package com.example.palabras





import android.media.Image
import android.provider.MediaStore




// Constants with max number of words per game and
// the score increase  on correct guesses
const val MAX_NO_OF_WORDS = 10
const val SCORE_INCREASE = 20

// Lists with groups of words
val countriesList: List<String> = listOf(
            "afghanistan",
            "albania",
            "algeria",
            "andorra",
            "angola",
            "antigua",
            "argentina",
            "armenia",
            "australia",
            "austria",
            "azerbaijan",
            "bahamas",
            "bahrain",
            "bangladesh",
            "barbados",
            "belarus",
            "belgium",
            "belize",
            "benin",
            "bhutan",
            "bolivia",
            "bosnia herzegovina",
            "botswana",
            "brazil",
            "brunei",
            "bulgaria",
            "burkina",
            "burundi",
            "cambodia",
            "cameroon",
            "canada",
            "cape verde",
            "chad",
            "chile",
            "china",
            "colombia",
            "comoros",
            "congo",
            "costa rica",
            "croatia",
            "cuba",
            "cyprus",
            "czech republic",
            "denmark",
            "djibouti",
            "dominica",
            "dominican republic",
            "ecuador",
            "egypt",
            "el salvador",
            //"equatorial guinea",
            "eritrea",
            "estonia",
            "ethiopia",
            "fiji",
            "finland",
            "france",
            "gabon",
            "gambia",
            "georgia",
            "germany",
            "ghana",
            "greece",
            "grenada",
            "guatemala",
            "guinea",
            "guinea-bissau",
            "guyana",
            "haiti",
            "honduras",
            "hungary",
            "iceland",
            "india",
            "indonesia",
            "iran",
            "iraq",
            "ireland",
            "italy",
    //"ivory coast", R.drawable.
            "jamaica",
            "japan",
            "jordan",
            "kazakhstan",
            "kenya",
            "kiribati",
            "korea north",
            "korea south",
            "kuwait",
            "kyrgyzstan",
            "laos",
            "latvia",
            "lebanon",
            "lesotho",
            "liberia",
            "libya",
            "liechtenstein",
            "lithuania",
            "luxembourg",
            "macedonia",
            "madagascar",
            "malawi",
            "malaysia",
            "maldives",
            "mali",
            "malta",
            "marshall islands",
            "mauritania",
            "mauritius",
            "mexico",
            "micronesia",
            "moldova",
            "monaco",
            "mongolia",
    //"montenegro", R.drawable.
            "morocco",
            "mozambique",
            "myanmar",
            "namibia",
            "nauru",
            "nepal",
            "netherlands",
            "new zealand",
            "nicaragua",
            "niger",
            "nigeria",
            "norway",
            "oman",
            "pakistan",
            "palau",
            "panama",
            "papua new guinea",
            "paraguay",
            "peru",
            "philippines",
            "poland",
            "portugal",
            "qatar",
            "romania",
            "russia",
            "rwanda",
            "st lucia",
            "samoa",
            "san marino",
            "saudi arabia",
            "senegal",
            "serbia",
            "seychelles",
            "sierra leone",
            "singapore",
            "slovakia",
            "slovenia",
            "solomon islands",
            "somalia",
            "south africa",
    //"south sudan", R.drawable.
            "spain",
            "sri lanka",
            "sudan",
            "suriname",
            "swaziland",
            "sweden",
            "switzerland",
            "syria",
            "taiwan",
            "tajikistan",
            "tanzania",
            "thailand",
            "togo",
            "tonga",
            "trinidad & tobago",
            "tunisia",
            "turkey",
            "turkmenistan",
            "tuvalu",
            "uganda",
            "ukraine",
            "united arab emirates",
            "united kingdom",
            "united states",
            "uruguay",
            "uzbekistan",
            "vanuatu",
            "vatican city",
            "venezuela",
            "vietnam",
            "yemen",
            "zambia",
            "zimbawe",
)

val countriesFlags: List<Int> = listOf(
    R.drawable.afghanistan,
    R.drawable.albania,
    R.drawable.algeria,
    R.drawable.andorra,
    R.drawable.angola,
    R.drawable.antigua_and_barbuda,
    R.drawable.argentina,
    R.drawable.armenia,
    R.drawable.australia,
    R.drawable.austria,
    R.drawable.azerbaijan,
    R.drawable.bahamas,
    R.drawable.bahrain,
    R.drawable.bangladesh,
    R.drawable.barbados,
    R.drawable.belarus,
    R.drawable.belgium,
    R.drawable.belize,
    R.drawable.benin,
    R.drawable.bhutan,
    R.drawable.bolivia,
    R.drawable.bosnia,
    R.drawable.botswana,
    R.drawable.brazil,
    R.drawable.brunei,
    R.drawable.bulgaria,
    R.drawable.burkina_faso,
    R.drawable.burundi,
    R.drawable.cambodia,
    R.drawable.cameroon,
    R.drawable.canada,
    R.drawable.cape_verde,
    R.drawable.chad,
    R.drawable.chile,
    R.drawable.china,
    R.drawable.colombia,
    R.drawable.comoros,
    R.drawable.democratic_republic_of_the_congo,
    R.drawable.costa_rica,
    R.drawable.croatia,
    R.drawable.cuba,
    R.drawable.cyprus,
    R.drawable.czech_republic,
    R.drawable.denmark,
    R.drawable.djibouti,
    R.drawable.dominica,
    R.drawable.dominican_republic,
    R.drawable.ecuador,
    R.drawable.egypt,
    R.drawable.el_salvador,
   // R.drawable.equatorial_guinea,
    R.drawable.eritrea,
    R.drawable.estonia,
    R.drawable.ethiopia,
    R.drawable.fiji,
    R.drawable.finland,
    R.drawable.france,
    R.drawable.gabon,
    R.drawable.gambia,
    R.drawable.georgia,
    R.drawable.germany,
    R.drawable.ghana,
    R.drawable.greece,
    R.drawable.grenada,
    R.drawable.guatemala,
    R.drawable.guinea,
    R.drawable.guinea_bissau,
    R.drawable.guyana,
    R.drawable.haiti,
    R.drawable.honduras,
    R.drawable.hungary,
    R.drawable.iceland,
    R.drawable.india,
    R.drawable.indonesia,
    R.drawable.iran,
    R.drawable.iraq,
    R.drawable.ireland,
    R.drawable.italy,
    R.drawable.jamaica,
    R.drawable.japan,
    R.drawable.jordan,
    R.drawable.kazakhstan,
    R.drawable.kenya,
    R.drawable.kiribati,
    R.drawable.north_korea,
    R.drawable.south_korea,
    R.drawable.kuwait,
    R.drawable.kyrgyzstan,
    R.drawable.laos,
    R.drawable.latvia,
    R.drawable.lebanon,
    R.drawable.lesotho,
    R.drawable.liberia,
    R.drawable.libya,
    R.drawable.liechtenstein,
    R.drawable.lithuania,
    R.drawable.luxembourg,
    R.drawable.macedonia,
    R.drawable.madagascar,
    R.drawable.malawi,
    R.drawable.malaysia,
    R.drawable.maldives,
    R.drawable.mali,
    R.drawable.malta,
    R.drawable.marshall_islands,
    R.drawable.mauritania,
    R.drawable.mauritius,
    R.drawable.mexico,
    R.drawable.micronesia,
    R.drawable.moldova,
    R.drawable.monaco,
    R.drawable.mongolia,
    R.drawable.morocco,
    R.drawable.mozambique,
    R.drawable.myanmar,
    R.drawable.namibia,
    R.drawable.nauru,
    R.drawable.nepal,
    R.drawable.netherlands,
    R.drawable.new_zealand,
    R.drawable.nicaragua,
    R.drawable.niger,
    R.drawable.nigeria,
    R.drawable.norway,
    R.drawable.oman,
    R.drawable.pakistan,
    R.drawable.palau,
    R.drawable.panama,
    R.drawable.papua_new_guinea,
    R.drawable.paraguay,
    R.drawable.peru,
    R.drawable.philippines,
    R.drawable.poland,
    R.drawable.portugal,
    R.drawable.qatar,
    R.drawable.romania,
    R.drawable.russian_federation,
    R.drawable.rwanda,
    R.drawable.saint_lucia,
    R.drawable.samoa,
    R.drawable.san_marino,
    R.drawable.saudi_arabia,
    R.drawable.senegal,
    R.drawable.serbia_and_montenegro,
    R.drawable.seychelles,
    R.drawable.sierra_leone,
    R.drawable.singapore,
    R.drawable.slovakia,
    R.drawable.slovenia,
    R.drawable.soloman_islands,
    R.drawable.somalia,
    R.drawable.south_africa,
    R.drawable.spain,
    R.drawable.sri_lanka,
    R.drawable.sudan,
    R.drawable.suriname,
    R.drawable.swaziland,
    R.drawable.sweden,
    R.drawable.switzerland,
    R.drawable.syria,
    R.drawable.taiwan,
    R.drawable.tajikistan,
    R.drawable.tanzania,
    R.drawable.thailand,
    R.drawable.togo,
    R.drawable.tonga,
    R.drawable.trinidad_and_tobago,
    R.drawable.tunisia,
    R.drawable.turkey,
    R.drawable.turkmenistan,
    R.drawable.tuvalu,
    R.drawable.uganda,
    R.drawable.ukraine,
    R.drawable.saudi_arabia,
    R.drawable.united_kingdom,
    R.drawable.united_states_of_america,
    R.drawable.uruguay,
    R.drawable.uzbekistan,
    R.drawable.vanuatu,
    R.drawable.vatican_city,
    R.drawable.venezuela,
    R.drawable.vietnam,
    R.drawable.yemen,
    R.drawable.zambia,
    R.drawable.zimbabwe,










)



